coverage_service: cobertura_xml
xcodeproj: ExpenseTracker.xcodeproj
input_format: profdata
output_directory: Coverage/
build_directory: build/Build/
scheme: ExpenseTracker
ignore:
  - ExpenseTrackerTests/*
  - ExpenseTrackerUITests/*
