# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Project
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Set Cocoapods
      run: |
        gem install cocoapods -v 1.15.2
        pod install --repo-update

    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 12.1

    - name: Build
      run: |
        set -o pipefail
        slather setup
        xcodebuild build-for-testing \
        -scheme ExpenseTracker \
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro' \
        -derivedDataPath build \
        | xcpretty

    - name: Archive derived data artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build

  test:
    name: Test Project
    needs: build
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Download derived data artifact
      uses: actions/download-artifact@v1
      with:
        name: build

    - name: Set Cocoapods
      run: |
        gem install cocoapods -v 1.15.2
        pod install --repo-update

    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 12.1

    - name: Test
      run: |
        set -o pipefail
        xcodebuild test-without-building \
        -scheme ExpenseTracker \
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro' \
        -derivedDataPath build \
        -enableCodeCoverage YES \
        | xcpretty

    - name: Coverage report
      run: slather coverage -x --binary-basename 'ExpenseTracker'

    - name: Post coverage
      uses: codecov/codecov-action@v1
      with:
        token: #{{ secrets.CODECOV_TOKEN }}
        file: ./Coverage/cobertura.xml
        fail_ci_if_error: true

